apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: floriano
spec:
  hard:
    requests.cpu: "5"
    requests.memory: "10Gi"
    limits.cpu: "20"
    limits.memory: "36Gi"
    pods: "10"
