apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sidekiq-bomjesus-scaledobject
  namespace: cuidar-bomjesus

spec:
  scaleTargetRef:
    name: sidekiq
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "90"
