apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: bomjesus
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "10Gi"
    limits.cpu: "20"
    limits.memory: "38Gi"
    pods: "15"
