apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: treinamento
spec:
  hard:
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "14"
    limits.memory: "22Gi"
    pods: "30"
