apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: saojoao-scaledobject
  namespace: cuidar-saojoao
spec:
  scaleTargetRef:
    name: saojoao
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"