apiVersion: v1
kind: Service
metadata:
  name: saojoao-service
  namespace: saojoao
spec:
  selector:
    app: saojoao
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP



