apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: elesbaoveloso-scaledobject
  namespace: elesbaoveloso
spec:
  scaleTargetRef:
    name: elesbaoveloso
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "90"
