apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: campomaior-scaledobject
  namespace: cuidar-campomaior
spec:
  scaleTargetRef:
    name: campomaior
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
    - type: memory
      metadata:
        type: Utilization
        value: "80"