---
# Kafka Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: saude-auditoria-gateway
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 9093
      targetPort: 9093
  selector:
    app: kafka
---
# Kafka Service (Client)
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: saude-auditoria-gateway
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
---
# Kafka StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: saude-auditoria-gateway
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - kafka
              topologyKey: kubernetes.io/hostname

      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: internal
              containerPort: 9092
            - name: external
              containerPort: 9093

          env:
            # Broker ID
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            # Zookeeper
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-0.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2181,zookeeper-1.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2181,zookeeper-2.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2181"

            # Listeners
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://$(POD_NAME).kafka-headless.saude-auditoria-gateway.svc.cluster.local:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            # Replication
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"

            # Performance
            - name: KAFKA_NUM_NETWORK_THREADS
              value: "3"
            - name: KAFKA_NUM_IO_THREADS
              value: "8"
            - name: KAFKA_SOCKET_SEND_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_SOCKET_RECEIVE_BUFFER_BYTES
              value: "102400"
            - name: KAFKA_SOCKET_REQUEST_MAX_BYTES
              value: "104857600"

            # Logs
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"  # 7 dias
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "1073741824"  # 1GB por partition
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "1073741824"
            - name: KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS
              value: "300000"

            # Partitions
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "false"  # Criar topics explicitamente

            # Group Coordinator
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "3000"

            # Compression
            - name: KAFKA_COMPRESSION_TYPE
              value: "snappy"

            # JVM
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1G -Xmx1G"
            - name: KAFKA_JVM_PERFORMANCE_OPTS
              value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"

            # Metrics
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: KAFKA_JMX_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            # Pod Name (para ADVERTISED_LISTENERS)
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          command:
            - bash
            - -c
            - |
              # Extrai o broker ID do hostname (kafka-0, kafka-1, kafka-2)
              export KAFKA_BROKER_ID=${HOSTNAME##*-}
              echo "Starting Kafka Broker ID: $KAFKA_BROKER_ID"

              # Aguarda Zookeeper estar pronto
              echo "Waiting for Zookeeper..."
              until echo ruok | nc zookeeper-0.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local 2181 | grep imok; do
                sleep 2
              done
              echo "Zookeeper is ready!"

              # Configura ADVERTISED_LISTENERS com o nome do pod
              export KAFKA_ADVERTISED_LISTENERS="INTERNAL://${POD_NAME}.kafka-headless.saude-auditoria-gateway.svc.cluster.local:9092"

              # Inicia Kafka
              exec /etc/confluent/docker/run

          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data

          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"

          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 50Gi
