---
# Zookeeper Service (Headless)
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: saude-auditoria-gateway
  labels:
    app: zookeeper
spec:
  clusterIP: None
  publishNotReadyAddresses: true  # Permite DNS antes de pods ficarem READY
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: server
      port: 2888
      targetPort: 2888
    - name: leader-election
      port: 3888
      targetPort: 3888
  selector:
    app: zookeeper
---
# Zookeeper Service (Client)
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: saude-auditoria-gateway
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
---
# Zookeeper StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: saude-auditoria-gateway
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - zookeeper
              topologyKey: kubernetes.io/hostname

      securityContext:
        fsGroup: 1000

      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.6.0
          imagePullPolicy: IfNotPresent

          ports:
            - name: client
              containerPort: 2181
            - name: server
              containerPort: 2888
            - name: leader-election
              containerPort: 3888

          env:
            - name: ZOOKEEPER_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOOKEEPER_SERVERS
              value: "zookeeper-0.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2888:3888;zookeeper-1.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2888:3888;zookeeper-2.zookeeper-headless.saude-auditoria-gateway.svc.cluster.local:2888:3888"
            - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
              value: "24"
            - name: ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
              value: "3"
            - name: ZOOKEEPER_MAX_CLIENT_CNXNS
              value: "60"
            - name: ZOOKEEPER_4LW_COMMANDS_WHITELIST
              value: "srvr,mntr,ruok"

          command:
            - bash
            - -c
            - |
              # Extrai o ID do pod (0, 1, 2)
              export ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+1))
              echo "Starting Zookeeper with ID: $ZOOKEEPER_SERVER_ID"

              # Configura myid
              echo $ZOOKEEPER_SERVER_ID > /var/lib/zookeeper/data/myid

              # Inicia Zookeeper
              exec /etc/confluent/docker/run

          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper/data
            - name: logs
              mountPath: /var/lib/zookeeper/log

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - echo ruok | nc localhost 2181 | grep imok
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - echo ruok | nc localhost 2181 | grep imok
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi

    - metadata:
        name: logs
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 5Gi
