apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demervallobao-scaledobject
  namespace: cuidar-demervallobao
spec:
  scaleTargetRef:
    name: demervallobao
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"