apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: demervallobao-scaledobject
  namespace: cuidar-demervallobao
spec:
  scaleTargetRef:
    name: demervallobao
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
    - type: memory
      metadata:
        type: Utilization
        value: "80"