---
# Kafka Exporter Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: saude-auditoria-gateway
  labels:
    app: kafka-exporter
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9308
      targetPort: 9308
  selector:
    app: kafka-exporter
---
# Kafka Exporter Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: saude-auditoria-gateway
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: kafka-exporter
          image: danielqsj/kafka-exporter:latest
          imagePullPolicy: IfNotPresent

          args:
            - --kafka.server=kafka-0.kafka-headless.kafka.svc.cluster.local:9092
            - --kafka.server=kafka-1.kafka-headless.kafka.svc.cluster.local:9092
            - --kafka.server=kafka-2.kafka-headless.kafka.svc.cluster.local:9092
            - --web.listen-address=:9308
            - --log.level=info
            - --topic.filter=saude\..*  # Regex para filtrar topics

          ports:
            - name: metrics
              containerPort: 9308

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9308
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9308
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
---
# ServiceMonitor para Prometheus Operator (opcional)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: saude-auditoria-gateway
  labels:
    app: kafka-exporter
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
