---
# Service ClusterIP para expor o NFS server internamente
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  namespace: shared-storage
  labels:
    app: nfs-server
spec:
  type: ClusterIP
  sessionAffinity: ClientIP  # Mantém conexões NFS estáveis
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
      protocol: TCP
    - name: mountd
      port: 20048
      targetPort: 20048
      protocol: TCP
    - name: rpcbind
      port: 111
      targetPort: 111
      protocol: TCP
  selector:
    app: nfs-server
