apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: raimundononato-scaledobject
  namespace: saoraimundononato
spec:
  scaleTargetRef:
    name: raimundononato
  minReplicaCount: 2
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"