apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sidekiq-raimundononato-scaledobject
  namespace: cuidar-raimundononato

spec:
  scaleTargetRef:
    name: sidekiq
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
