apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: raimundononato-scaledobject
  namespace: cuidar-raimundononato
spec:
  scaleTargetRef:
    name: raimundononato
  minReplicaCount: 3
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"