apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: saoraimundononato
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "20Gi"
    limits.cpu: "22"
    limits.memory: "42Gi"
    pods: "15"
