apiVersion: v1
kind: Service
metadata:
  name: raimundononato-service
  namespace: raimundononato
spec:
  selector:
    app: raimundononato
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP



