apiVersion: v1
kind: Service
metadata:
  name: parnaiba-service
  namespace: parnaiba
  labels:
    app: parnaiba
    environment: production
spec:
  selector:
    app: parnaiba
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
