apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv-floriano
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  azureFile:
    secretName: azure-secret
    shareName: stcuidarnew01
    readOnly: false
    secretNamespace: default
