apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-readmodel-pvc
  namespace: saude-bi
  labels:
    app: postgres-readmodel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
