---
# Airflow Webserver Service
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: saude-airflow
  labels:
    app: airflow
    component: webserver
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: airflow
    component: webserver
---
# Airflow Webserver Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: saude-airflow
  labels:
    app: airflow
    component: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: airflow
      component: webserver
  template:
    metadata:
      labels:
        app: airflow
        component: webserver
    spec:
      serviceAccountName: airflow
      imagePullSecrets:
        - name: acr-secret

      initContainers:
        # Init container para esperar o banco estar pronto
        - name: wait-for-db
          image: postgres:13
          command:
            - sh
            - -c
            - |
              until pg_isready -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER; do
                echo "Waiting for database..."
                sleep 2
              done
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-user
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: POSTGRES_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: POSTGRES_PORT
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

        # Init container para inicializar o banco de dados do Airflow
        - name: airflow-db-init
          image: apache/airflow:3.0.6
          command:
            - bash
            - -c
            - |
              airflow db check || airflow db migrate
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: sql-alchemy-conn
            - name: AIRFLOW__API__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: webserver-secret-key
          volumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"

      containers:
        - name: webserver
          image: apache/airflow:3.0.6
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              # Criar usuário admin se não existir
              airflow users create \
                --username admin \
                --firstname Admin \
                --lastname User \
                --email admin@saude.gov.br \
                --role Admin \
                --password ${ADMIN_PASSWORD:-admin} || true

              # Iniciar api-server (novo comando no Airflow 3.x)
              exec airflow api-server

          ports:
            - containerPort: 8080
              name: http

          envFrom:
            - configMapRef:
                name: airflow-config

          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: sql-alchemy-conn
            - name: AIRFLOW__API__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: webserver-secret-key
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: webserver-secret-key
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-admin-secret
                  key: admin-password

          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
              readOnly: true
            - name: logs
              mountPath: /opt/airflow/logs
            - name: pod-template
              mountPath: /opt/airflow/pod_templates
              readOnly: true

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          livenessProbe:
            httpGet:
              path: /public/api/v1/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /public/api/v1/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: pod-template
          configMap:
            name: airflow-pod-template
