---
# Airflow Scheduler Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: saude-airflow
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1  # Apenas 1 scheduler para evitar conflitos
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      serviceAccountName: airflow
      imagePullSecrets:
        - name: acr-secret

      initContainers:
        # Init container para esperar o banco estar pronto
        - name: wait-for-db
          image: postgres:13
          command:
            - sh
            - -c
            - |
              until pg_isready -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER; do
                echo "Waiting for database..."
                sleep 2
              done
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-user
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: POSTGRES_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: airflow-config
                  key: POSTGRES_PORT

      containers:
        - name: scheduler
          image: apache/airflow:3.0.6
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -c
            - |
              exec airflow scheduler

          envFrom:
            - configMapRef:
                name: airflow-config

          env:
            - name: AIRFLOW__CORE__FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: fernet-key
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: sql-alchemy-conn
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: webserver-secret-key

          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
              readOnly: true
            - name: logs
              mountPath: /opt/airflow/logs
            - name: pod-template
              mountPath: /opt/airflow/pod_templates
              readOnly: true

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  airflow jobs check --job-type SchedulerJob --hostname $(hostname)
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5

      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: pod-template
          configMap:
            name: airflow-pod-template
