apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: saude-homolog
spec:
  limits:
    - type: Container
      default:
        cpu: "1.25"
        memory: "2.5Gi"
      defaultRequest:
        cpu: "400m"
        memory: "768Mi"
