apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: saude-homolog
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: "2Gi"
      defaultRequest:
        cpu: "300m"
        memory: "512Mi"
