apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: saude-homolog
spec:
  hard:
    requests.cpu: "6"
    requests.memory: "12Gi"
    limits.cpu: "10"
    limits.memory: "18Gi"
    pods: "30"
