apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: saude-homolog
type: Opaque
stringData:
  # Database Credentials (AWS RDS via Proxy)
  DATABASE_PASSWORD: "rM9$8wRW8V*&lxzD"
  DATABASE_USERNAME: postgres

  # Database Connection Strings (via RDS Proxy with TLS)
  # RDS Proxy endpoint: proxy-db-viverdb.proxy-cb8m6qcy2cyh.sa-east-1.rds.amazonaws.com
  # NOTE: sslmode=require is mandatory for RDS Proxy
  # Rails Secret Key
  SECRET_KEY_BASE: 8c4d9f264ea397f4767e4fc24a68a95b88d0787048711fc841e65bb33cd1e64500be8140751470177dbf55842f267b52f9e2f744e43692ee16efe57b99860580

  # API Tokens
  HIDRA_TOKEN: 882ILCri93gsJpQvzgUbTQtt

  # Monitoring (contains token)
  SENTRY_URL: https://11b50674bb1c6fd8c409352cc70967f3@sentry.bigdatasys.net/5
