apiVersion: v1
kind: ServiceAccount
metadata:
  name: cuidar-sigtap-sa
  namespace: saude-homolog
  labels:
    app.kubernetes.io/name: cuidar
    app.kubernetes.io/component: sigtap-s3
  annotations:
    # IRSA — role compartilhada entre tenants (trust: system:serviceaccount:*:cuidar-sigtap-sa)
    eks.amazonaws.com/role-arn: arn:aws:iam::961341521437:role/cuidar-sigtap-s3
