apiVersion: v1
kind: LimitRange
metadata:
  name: saude-auditoria-gateway-limits
  namespace: saude-auditoria-gateway
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
