apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: piripiri-scaledobject
  namespace: cuidar-piripiri
spec:
  scaleTargetRef:
    name: piripiri
  minReplicaCount: 2
  maxReplicaCount: 8
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "70"
    - type: memory
      metricType: Utilization
      metadata:
        value: "90"