apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile-pvc
  namespace: piripiri
  labels:
    app: piripiri
spec:
  accessModes:
    - ReadWriteOnce  # EBS RWO + podAffinity para escalar no mesmo node
  storageClassName: gp3  # AWS EBS gp3
  resources:
    requests:
      storage: 100Gi
