apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: piripiri
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "50Gi"
    pods: "20"
