apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: piripiri
spec:
  hard:
    requests.cpu: "18"
    requests.memory: "60Gi"
    limits.cpu: "36"
    limits.memory: "80Gi"
    pods: "20"
