apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: piripiri
spec:
  hard:
    requests.cpu: "20"
    requests.memory: "65Gi"
    limits.cpu: "40"
    limits.memory: "90Gi"
    pods: "20"
