apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: srn-homolog-scaledobject
  namespace: saude-srn
spec:
  scaleTargetRef:
    name: srnhomolog
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"