apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: miguelalves-scaledobject
  namespace: cuidar-miguelalves
spec:
  scaleTargetRef:
    name: miguelalves
  minReplicaCount: 2
  maxReplicaCount: 5
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"