apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-cache-pvc
  namespace: c-tv
spec:
  accessModes:
    - ReadWriteOnce  # RWO - gp2/gp3 padrão (sem EFS)
  resources:
    requests:
      storage: 10Gi
  # storageClassName: gp2  # Descomente se precisar especificar
  # Nota: Sem storageClassName usa o padrão do cluster (geralmente gp2 ou gp3)