apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-pdb
  namespace: c-tv
  labels:
    app.kubernetes.io/name: c-tv
    app.kubernetes.io/component: web
spec:
  minAvailable: 2
  selector:
    matchLabels:
      io.kompose.service: web