apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: c-tv
  labels:
    io.kompose.service: web
    app.kubernetes.io/name: c-tv
    app.kubernetes.io/component: web
spec:
  selector:
    io.kompose.service: web
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  type: ClusterIP