---
# ConfigMap: Nginx configuration with JSON access logs
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sidecar-pageview-config
  namespace: picos  # Aplicar para cada namespace
data:
  nginx.conf: |
    worker_processes  1;

    events {
      worker_connections  1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      # JSON access log format for PAGE_VIEW tracking
      log_format json_pageview escape=json '{'
        '"timestamp":"$time_iso8601",'
        '"remote_addr":"$remote_addr",'
        '"request_method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"status":$status,'
        '"request_time":$request_time,'
        '"http_user_agent":"$http_user_agent",'
        '"http_referer":"$http_referer"'
        '}';

      access_log /var/log/nginx/access.log json_pageview;

      sendfile        on;
      keepalive_timeout  65;

      # Compression
      gzip              on;
      gzip_comp_level   5;
      gzip_types        text/plain text/css application/json application/javascript application/x-javascript image/svg+xml;
      gzip_min_length   1024;

      server {
        listen 80;

        # Serve static assets directly
        location ~ ^/(assets|stylesheets|javascripts)/ {
          root /app/public;
          try_files $uri $uri/ =404;
          add_header Cache-Control "public, max-age=31536000, immutable";
          access_log off;  # Não logar assets estáticos
        }

        # Proxy everything else to Puma
        location / {
          proxy_pass         http://127.0.0.1:3000;
          proxy_http_version 1.1;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Proto $scheme;
          proxy_connect_timeout 300s;
          proxy_send_timeout    300s;
          proxy_read_timeout    300s;
        }
      }
    }

---
# ConfigMap: Fluent Bit configuration to process nginx logs
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-pageview-config
  namespace: picos  # Aplicar para cada namespace
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Daemon        off
        Log_Level     info

    [INPUT]
        Name              tail
        Path              /var/log/nginx/access.log
        Parser            json
        Tag               nginx.access
        Refresh_Interval  5
        Mem_Buf_Limit     5MB

    [FILTER]
        Name    lua
        Match   nginx.access
        script  /fluent-bit/scripts/pageview_filter.lua
        call    filter_pageview

    [OUTPUT]
        Name   http
        Match  nginx.pageview
        Host   saude-auditoria-gateway.saude-auditoria-gateway.svc.cluster.local
        Port   80
        URI    /events
        Format json
        Header X-Audit-Signature ${AUDITORIA_GATEWAY_SECRET_HMAC}
        retry_limit 3

  pageview_filter.lua: |
    function filter_pageview(tag, timestamp, record)
        -- Filtrar apenas GETs com status 200-399
        if record.request_method ~= "GET" then
            return -1, 0, 0  -- Drop event
        end

        local status = tonumber(record.status) or 0
        if status < 200 or status >= 400 then
            return -1, 0, 0  -- Drop non-success responses
        end

        local uri = record.request_uri or ""

        -- Filtrar assets, health checks, etc
        if string.match(uri, "^/assets") or
           string.match(uri, "^/packs") or
           string.match(uri, "^/health") or
           string.match(uri, "^/cable") or
           string.match(uri, "^/rails") or
           string.match(uri, "^/api/") or
           string.match(uri, "%.js$") or
           string.match(uri, "%.css$") or
           string.match(uri, "%.png$") or
           string.match(uri, "%.jpg$") or
           string.match(uri, "%.jpeg$") or
           string.match(uri, "%.gif$") or
           string.match(uri, "%.svg$") or
           string.match(uri, "%.ico$") then
            return -1, 0, 0  -- Drop assets/excluded paths
        end

        -- Construir evento PAGE_VIEW
        local cluster = os.getenv("APP_HOST") or "unknown"
        local new_record = {
            event_type = "PAGE_VIEW",
            timestamp = os.date("!%Y-%m-%dT%H:%M:%SZ"),
            caminho = uri,
            cluster = cluster
        }

        return 2, timestamp, new_record  -- Modify record and change tag
    end
