apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: learning-scaledobject
  namespace: saude-learning
spec:
  scaleTargetRef:
    name: learning
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
    - type: memory
      metadata:
        type: Utilization
        value: "90"