apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: isac-homolog-scaledobject
  namespace: cuidar-isac-hml
spec:
  scaleTargetRef:
    name: isachomolog
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"
    - type: memory
      metadata:
        type: Utilization
        value: "80"