apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "94aff3d1-b27d-4f74-aa33-e64b219b77ed"
  labels:
    azure.workload.identity/use: "true"
  name: saude-event-agent-sa
  namespace: saude-event-agent