apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: apresentacao-scaledobject
  namespace: cuidar-apresentacao
spec:
  scaleTargetRef:
    name: apresentacao
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
    - type: memory
      metadata:
        type: Utilization
        value: "50"