apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: corrente
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "12Gi"
    limits.cpu: "22"
    limits.memory: "40Gi"
    pods: "15"
