apiVersion: v1
kind: Service
metadata:
  name: corrente-service
  namespace: corrente
spec:
  selector:
    app: corrente
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: ClusterIP



