apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sidekiq-picos-scaledobject
  namespace: cuidar-picos
spec:
  scaleTargetRef:
    name: sidekiq
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60"