apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: picos-scaledobject
  namespace: picos
spec:
  scaleTargetRef:
    name: picos
  minReplicaCount: 3
  maxReplicaCount: 6
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "80"
