apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute
  namespace: picos
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "12"
    limits.memory: "30Gi"
    pods: "10"
