apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: curimata-scaledobject
  namespace: curimata
spec:
  scaleTargetRef:
    name: curimata
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "90"
