apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: luzilandia-scaledobject
  namespace: luzilandia
spec:
  scaleTargetRef:
    name: luzilandia
  minReplicaCount: 1
  maxReplicaCount: 4
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "60"
    - type: memory
      metricType: Utilization
      metadata:
        value: "90"
