apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: edne-endereco
  labels:
    app: opensearch
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: opensearch
