apiVersion: v1
kind: Service
metadata:
  name: opensearch-headless
  namespace: edne-endereco
  labels:
    app: opensearch
spec:
  clusterIP: None
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    app: opensearch
